/**
 * Selectors for the TodayPage component.
 *
 * Originally generated by `ppg workspace ./frontend -o ./e2e`; the
 * generated catch-alls (`button`, `p`) were hand-refined to the stable
 * `sh-*` component selectors and class hooks the implementation owns.
 */
export const todayPageSelectors = {
  /** Greeting heading ("Shalom, <name>") */
  greeting: 'h1.greeting',
  /** Local date line above the greeting */
  date: '.page-head .date',

  /** Verse card and its parts */
  verseCard: 'sh-verse-card',
  verseText: 'sh-verse-card .text',
  verseReference: 'sh-verse-card .reference',
  verseLink: 'sh-verse-card a.link',

  /** Check-in card */
  checkInSection: 'section.check-in',
  morningCheckInHeading: 'h2:has-text("Morning check-in")',
  ratingChips: 'sh-rating-chips button.chip',
  dots: 'sh-dot-scale button.dot',
  noteInput: 'input.note',
  saveButton: 'button.save',
  savedBadge: '.saved-badge',

  /** Reading card */
  readingCard: 'sh-reading-card',
  readingPlanName: 'sh-reading-card .plan',
  readingPassage: 'sh-reading-card .passage',
  readingProgress: 'sh-reading-card .progress',
  readingLink: 'sh-reading-card a.link',
  markReadButton: 'sh-reading-card button.mark-read',
  readingDone: 'sh-reading-card .done',

  /** Connection card (server-selected daily nudge) */
  connectionCard: '[data-testid="sh-today-connection"]',
  connectionPrompt: '[data-testid="sh-today-connection-prompt"]',
  connectionText: '[data-testid="sh-today-connection-text"]',
  connectionDone: '[data-testid="sh-today-connection-done"]',
  connectionSnooze: '[data-testid="sh-today-connection-snooze"]',
  upcomingDate: '[data-testid="sh-today-upcoming-date"]',

  /** Derived streak line at the foot of the page */
  streaks: 'p.streaks',
} as const;
