/**
 * Selectors for the TodayPage component.
 *
 * Originally generated by `ppg workspace ./frontend -o ./e2e`; hand-refined
 * to the stable `sh-*`/`data-testid` hooks the implementation owns. M6
 * replaced the flat dashboard with the time-aware composition (morning /
 * midday / evening / night) — the check-in, verse, and reading hooks moved
 * into the ritual (see `ritual-page.selectors.ts`).
 */
export const todayPageSelectors = {
  /** Header (hidden in the night band) */
  greeting: 'h1.greeting',
  date: '.page-head .date',
  avatar: '[data-testid="sh-today-avatar"]',
  statusPill: '[data-testid="sh-today-status-pill"]',

  /** Morning hero ↔ compact morning-complete card */
  ritualHero: '[data-testid="sh-ritual-hero"]',
  ritualBegin: '[data-testid="sh-ritual-begin"]',
  morningComplete: '[data-testid="sh-today-morning-complete"]',
  stillHere: '[data-testid="sh-today-still-here"]',
  dayBadge: '[data-testid="sh-today-day-badge"]',

  /** Fasting card */
  fastingCard: '[data-testid="sh-today-fasting"]',
  fastingElapsed: '[data-testid="sh-today-fasting-elapsed"]',
  fastingWindow: '[data-testid="sh-today-fasting-window"]',

  /** Eating window (midday) and closing countdown (evening) */
  eatingWindow: '[data-testid="sh-today-eating-window"]',
  logMeal: '[data-testid="sh-today-log-meal"]',
  windowCountdown: '[data-testid="sh-today-window-countdown"]',
  windowClosing: '[data-testid="sh-today-window-closing"]',

  /** Movement */
  movementCard: '[data-testid="sh-today-movement"]',
  /** Append the equipment value, e.g. `sh-today-intention-IndoorBike"]`. */
  intentionChipPrefix: '[data-testid="sh-today-intention-',
  eveningMovement: '[data-testid="sh-today-evening-movement"]',
  movementDismiss: '[data-testid="sh-today-movement-dismiss"]',

  /** Connection card (server-selected daily nudge) */
  connectionCard: '[data-testid="sh-today-connection"]',
  connectionPrompt: '[data-testid="sh-today-connection-prompt"]',
  connectionText: '[data-testid="sh-today-connection-text"]',
  connectionCall: '[data-testid="sh-today-connection-call"]',
  connectionDone: '[data-testid="sh-today-connection-done"]',
  connectionSnooze: '[data-testid="sh-today-connection-snooze"]',
  upcomingDate: '[data-testid="sh-today-upcoming-date"]',

  /** Tomorrow glance (evening) */
  tomorrow: '[data-testid="sh-today-tomorrow"]',

  /** Discovery slot (one card max) */
  discovery: '[data-testid="sh-today-discovery"]',
  discoveryCta: '[data-testid="sh-discovery-cta"]',
  discoveryDismiss: '[data-testid="sh-discovery-dismiss"]',

  /** Night rest state */
  night: '[data-testid="sh-today-night"]',

  /** Derived streak line at the foot of the page (hidden before day 3) */
  streaks: 'p.streaks',
} as const;
